### ISSUE TITLE
Communication on this blog can be enhanced

### ISSUE THREAD

**Issue by jingyig01** [VCVina/VCVina.github.io#1]
Hi, VCVina,
     I'm Jingyi, a new reader of your blog 'Miracle for me'. Your essay on  universities of Japan and China have impressed me a lot. Natually, I would like to find a way to post my comments, or at least to communicate with the author. Therefore it's very sad for me to find that your blog has neither comment system nor ways to contact you.  In addition, you haven't add RSS source to that website, which means I cannot subscrbe your blog via news aggregator application like Feedly. Maybe you can consider fixing these problems in order to get a better communication with your readers.
   My apologies if this issue disturbed you.
Best wishes,
Jingyi

**Comment by VCVina** [comment]
To jingyig01

I have received and read your suggestions. 
First of all, thank you very much for your advice.
Because of political inclination, I **have no plan to add email address** in order to ensure personal and family safety and reduce harassment for the time being.
But **Comments System and RSS are under consideration**.
Thank you for your proposal.

VCVina
